DROP TABLE IF EXISTS IATA_CODES;
DROP TABLE IF EXISTS CURRENCIES;
DROP TABLE IF EXISTS FLIGHT_SEARCHES;

CREATE TABLE IATA_CODES(
    CODE CHAR(3) PRIMARY KEY,
    CITY VARCHAR (100) NOT NULL,
    TERM VARCHAR (100) NOT NULL,
    COUNTRY VARCHAR (100) NOT NULL,
    MULTIPLE_AIRPORTS BOOLEAN NOT NULL
 ) ;

CREATE TABLE CURRENCIES(
    ID INT PRIMARY KEY,
    ISO CHAR (3) NOT NULL
 ) ;

CREATE TABLE FLIGHT_SEARCHES(
    ID INT PRIMARY KEY,
    RESULT CLOB NOT NULL
 ) ;
